import "server-only";

import {
  DEFAULT_OPENAI_MODEL,
  DEFAULT_OPENAI_TIMEOUT_MS,
  DEFAULT_OPENAI_VECTOR_STORE_FILE_CHUNKING_STRATEGY,
  MAX_OPENAI_VECTOR_STORE_FILE_MAX_CHUNK_SIZE_TOKENS,
  MIN_OPENAI_VECTOR_STORE_FILE_MAX_CHUNK_SIZE_TOKENS,
  parseOpenAIServerEnv,
} from "./env-core";

export {
  DEFAULT_OPENAI_MODEL,
  DEFAULT_OPENAI_TIMEOUT_MS,
  DEFAULT_OPENAI_VECTOR_STORE_FILE_CHUNKING_STRATEGY,
  MAX_OPENAI_VECTOR_STORE_FILE_MAX_CHUNK_SIZE_TOKENS,
  MIN_OPENAI_VECTOR_STORE_FILE_MAX_CHUNK_SIZE_TOKENS,
  parseOpenAIServerEnv,
};
export type { OpenAIServerEnv } from "./env-core";

export const openAIServerEnv = parseOpenAIServerEnv(process.env);
